version: '3'
services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./painting_recognition:/app/painting_recognition
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    links:
      - qdrant