FROM python:3.11

# Path: /app
WORKDIR /app

COPY . .
RUN pip install poetry==1.8.1 && \
    poetry config virtualenvs.create false
RUN poetry install --no-dev

# Mount volume to /app/painting_recognition
ENTRYPOINT poetry run uvicorn painting_recognition:app --reload --host 0.0.0.0